---
name: bump version
on:
  workflow_call: {}
  repository_dispatch:
    types: [bump-version-command]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  BOT_EMAIL: cloudorchestrator+github-bot@sap.com
  BOT_NAME: co-actions[bot]
  # Common versions
  # renovate: datasource=github-tags depName=golangci/golangci-lint
  GOLANGCI_VERSION: 'v1.53.3'
  # renovate: datasource=go depName=golang.org/x/tools/cmd/goimports
  GO_IMPORT_VERSION: 'v0.1.12'
  DOCKER_BUILDX_VERSION: 'v0.8.2'
  GOPRIVATE: "github.tools.sap/*"

jobs:
  generate:
    runs-on: ubuntu-latest 
    container:
      image: golang:1.20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
      - name: Vars for version bumping
        id: vars
        run: |
          versiontype=${{ github.event.client_payload.slash_command.args.named.versiontype }}
          if [[ -z "$versiontype" ]]; then versiontype="patch"; fi
          fromversion=$(cat VERSION)        
          echo "versiontype=$versiontype" >> "$GITHUB_ENV"
          echo "fromversion=$fromversion" >> "$GITHUB_ENV"            
      - name: Configure git
        run: |
          git config --global --add safe.directory "$(pwd)"
          git config --global url.https://${{ secrets.REPOSITORY_SETTINGS_TOKEN }}@github.tools.sap/.insteadOf https://github.tools.sap/
          git config --global user.email "${{ env.BOT_EMAIL }}"
          git config --global user.name "${{ env.BOT_NAME }}"
      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Find the Go Build Cache
        id: go
        run: echo "::set-output name=cache::$(go env GOCACHE)"

      - name: Cache the Go Build Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.go.outputs.cache }}
          key: ${{ runner.os }}-build-check-diff-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-check-diff-
      - name: Install bumper utils
        run: |
          go install github.tools.sap/cloud-orchestration/bump_version@1.0.0
      - name: bump version 
        run: |
          toversion=$(echo $(bump_version ${{ env.versiontype }}))
          echo "toversion=$toversion" >> "$GITHUB_ENV"
          echo $toversion > VERSION
      - name: Count Changes
        shell: bash
        run: |
          set -euo pipefail
          NUMCHANGES=$(git status -s | wc -l || exit 1)
          echo "changes=$NUMCHANGES" >> $GITHUB_ENV
      - name: Commit & push
        if: "${{ env.changes != '0' }}"
        run: |
          git config --global user.email "${{ env.BOT_EMAIL }}"
          git add VERSION
          git commit -m "${{ github.event.client_payload.slash_command.command }} for ${{ github.event.client_payload.github.payload.comment.user.login }}. See ${{ github.event.client_payload.github.payload.comment.html_url }}"
          git push
      - name: Update comment (success)
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >successfully ran /${{ github.event.client_payload.slash_command.command }}
            >updated version from ${{ env.fromversion }} to ${{ env.toversion }} 
            >${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          reactions: hooray
          reactions-edit-mode: replace

      - name: Update comment (fail)
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            >failed to run /${{ github.event.client_payload.slash_command.command }}
            >${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          reactions: confused
          reactions-edit-mode: replace
