---
name: Command Dispatch
on:
  workflow_call: {}
  issue_comment:
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubunutu
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            bump-version
